### ISSUE TITLE
Add branch protection for main

### ISSUE THREAD

**Issue by alanvardy** [CorneliaKelinske/ex_quiz_it#2]
Hello,

Could we add branch protection for main requiring:

- One approval before a PR can be merged, and
- Cannot push to main (only merge in PRs)

This would give us some guardrails going forwards, it is in the repository options

**Comment by CorneliaKelinske** [comment]
@alanvardy For sure!
I am going to do that after we complete the standard basic set-up  (tool_versions and tooling)

**Comment by CorneliaKelinske** [comment]
Done!  :)
