### ISSUE TITLE
Allow force pushing to branches (just not to main)

### ISSUE THREAD

**Issue by alanvardy** [CorneliaKelinske/ex_quiz_it#4]
![image](https://user-images.githubusercontent.com/38899847/194645836-6233f037-4269-44de-8dd0-e2a1f2c164e3.png)

Hello, I am hoping to be able to force push to the branch I am working on but still not be able to force push to main. You can put a filter of `main` on branch protection to only have it apply to main.

Thank you!

**Comment by CorneliaKelinske** [comment]
should be done now

**Comment by alanvardy** [comment]
Thank you, closing the issue

**Comment by alanvardy** [comment]
Confirmed working, cheers!
